server {
    listen 80;
    listen [::]:80;
    server_name sarteaga.dev www.sarteaga.dev;

    # Redirección automática de HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Ruta para el desafío de Let's Encrypt (Certbot)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name sarteaga.dev www.sarteaga.dev;

    # Rutas a los certificados SSL (los generaremos en la Fase 4)
    ssl_certificate /etc/letsencrypt/live/sarteaga.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sarteaga.dev/privkey.pem;

    # Configuración de seguridad recomendada
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Clave para React Router
    }
}