export const iconMap = {
    "Python": { slug: "python", color: "3776AB" },
    "JavaScript": { slug: "javascript", color: "F7DF1E" },
    "TypeScript": { slug: "typescript", color: "3178C6" },
    "Java": { slug: "openjdk", color: "FFFFFF" },
    "SQL": { slug: "postgresql", color: "4169E1" },
    "Django": { slug: "django", color: "092E20" },
    "Node.js": { slug: "nodedotjs", color: "5FA04E" },
    "NestJS": { slug: "nestjs", color: "E0234E" },
    "Express.js": { slug: "express", color: "FFFFFF" },
    "Odoo ERP": { slug: "odoo", color: "714B67" },
    "PostgreSQL": { slug: "postgresql", color: "4169E1" },
    "MySQL": { slug: "mysql", color: "4479A1" },
    "MongoDB": { slug: "mongodb", color: "47A248" },
    "Git": { slug: "git", color: "F05032" },
    "GitHub": { slug: "github", color: "FFFFFF" },
    "Docker": { slug: "docker", color: "2496ED" },
    // "VS Code": { slug: "visual studio", color: "007ACC" },
    "Postman": { slug: "postman", color: "FF6C37" },
    "HTML/CSS": { slug: "html5", color: "E34F26" },
    "Bootstrap": { slug: "bootstrap", color: "7952B3" },
    "React": { slug: "react", color: "61DAFB" },
    "Tailwind CSS": { slug: "tailwindcss", color: "06B6D4" },
};